IdentityTask/Controllers/Admin/AdminBrandsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IdentityTask.Models;
using System.IO;

namespace IdentityTask.Controllers.Admin
{
    [Authorize(Roles ="Admin")]
    public class AdminBrandsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AdminBrands
        public ActionResult Index()
        {
            return View(db.Brands.ToList());
        }

        // GET: AdminBrands/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // GET: AdminBrands/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminBrands/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Description,BrandImg,AdminID")] Brand brand,HttpPostedFileBase BrandImg)
        {
            if (ModelState.IsValid)
            {
                db.Brands.Add(brand);
                db.SaveChanges();
                string brandImgURL = brand.ID + "_" + BrandImg.FileName;
                BrandImg.SaveAs(Server.MapPath("~/Images/BrandsImages/") + brandImgURL);
                brand.BrandImg = brandImgURL;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(brand);
        }

        // GET: AdminBrands/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // POST: AdminBrands/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Description,BrandImg,AdminID")] Brand brand,HttpPostedFileBase BrandImg)
        {
            if (ModelState.IsValid)
            {
                db.Entry(brand).State = EntityState.Modified;

                db.SaveChanges();
                FileInfo fi = new FileInfo(brand.BrandImg);
                fi.Delete();
                string brandImgURL = brand.ID + "_" + BrandImg.FileName;
                BrandImg.SaveAs(Server.MapPath("~/Images/BrandsImages/") + brandImgURL);
                brand.BrandImg = brandImgURL;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(brand);
        }

        // GET: AdminBrands/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // POST: AdminBrands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Brand brand = db.Brands.Find(id);
            
           var ProductsInBrand= db.Products.Where(a => a.BrandID==id).ToList();
            foreach (var item in ProductsInBrand)
            {
                item.BrandID = null;
            }
            db.Brands.Remove(brand);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IdentityTask/Views/AdminBrands/Create.cshtml
@model IdentityTask.Models.Brand

@{
    ViewBag.Name = "Create Brand";
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create","AdminBrands",FormMethod.Post,new { enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Brand</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrandImg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="BrandImg"/>
                @Html.ValidationMessageFor(model => model.BrandImg, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

IdentityTask/Views/AdminBrands/Delete.cshtml
@model IdentityTask.Models.Brand

@{
    ViewBag.Name="Delete Brand";
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}



<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Brand</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BrandImg)
        </dt>

        <dd>
            <img src="~/Images/BrandsImages/@Model.BrandImg" style="border-radius:50%" width="70px" height="70px" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        



    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

IdentityTask/Views/AdminBrands/Details.cshtml
@model IdentityTask.Models.Brand

@{
    ViewBag.Name = "Brand Details";
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Brand</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BrandImg)
        </dt>

        <dd>
            <img src="~/Images/BrandsImages/@Model.BrandImg" style="border-radius:50%" width="70px" height="70px"/>
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>





    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IdentityTask/Views/AdminBrands/Edit.cshtml
@model IdentityTask.Models.Brand

@{
    ViewBag.Name = "Edit Brand";
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit","AdminBrands",FormMethod.Post,new { enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Brand</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrandImg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               <input type="file" name="BrandImg"/>
                @Html.ValidationMessageFor(model => model.BrandImg, "", new { @class = "text-danger" })
            </div>
        </div>

        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

IdentityTask/Views/AdminBrands/Index.cshtml
@model IEnumerable<IdentityTask.Models.Brand>

@{
    ViewBag.Name = "Brands";
    ViewBag.Title = "Index";

    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}




@Html.ActionLink("Add Brand", "Create", "AdminBrands", new { @class = "btn btn-success ", style = "margin-top:5px;margin-left:5px" })
<div style="margin:5px" >
    <span style="font:30px bold verdana">Search : </span><input type="text" id="txtSearch" class="form-search" style="border-radius:10%;padding:5px" />

</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(a => a.BrandImg)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>


        <th>OPerations</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <img src="~/Images/BrandsImages/@item.BrandImg" style="border-radius:50%" width="50px" height="50px" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>


            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>
@section script{
    <script>
        $(function () {
            $("#txtSearch").keyup(function () {
                var userInput = $(this).val();
                $("table:first tr:gt(0)").each(function (index, element) {
                    var currentValue = $(this).children("td:eq(1)")()
                })
                
            })
        })
    </script>
    
    }