IdentityTask/Controllers/Admin/AdminProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IdentityTask.Models;
using PagedList;
using System.Data.Entity;
using System.Net;
using PagedList.Mvc;
using System.IO;

namespace IdentityTask.Controllers.Admin
{
    [Authorize(Roles ="Admin")]
    public class AdminProductsController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: AdminProducts
        public ActionResult Index(int? page,string SortOrder)
        {

          
            var products = db.Products.Include(p => p.Brand).Include(p => p.Category);

            ViewBag.CurrentSort = SortOrder;
            ViewBag.IDSort = String.IsNullOrEmpty(SortOrder) ? "IDSort" : "";
            ViewBag.RateSort = SortOrder== "RateSort" ? "RateSort" : "";
            ViewBag.PriceSort = SortOrder == "PriceSort" ? "PriceSort" : "";

            switch (SortOrder)
            {
                case "IDSort":
                    products = products.OrderBy(a => a.ID);
                    break;
                case "RateSort":
                    products = products.OrderBy(a => a.Rate);
                    break;
                case "PriceSort":
                    products = products.OrderBy(a => a.Price);
                    break;
                default:
                    products = products.OrderBy(a => a.ID);
                    break;
            }


            var pageNumber = page ?? 1;
            var ProductsPerPage = products.ToPagedList(pageNumber, 3);
            ViewBag.ProductsPerPage = ProductsPerPage;

            return View(ProductsPerPage.ToList());
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.NotFound);
            }
            var product = db.Products.FirstOrDefault(a => a.ID == id);
            return View(product);
        }
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories.ToList(), "ID", "Name");
            ViewBag.BrandID = new SelectList(db.Brands.ToList(), "ID", "Name");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product product, HttpPostedFileBase ImageURL)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                string NewImageURL = product.ID + "." + ImageURL.FileName.Split('.')[1];
                ImageURL.SaveAs(Server.MapPath("~/Images/ProductsImages/") + NewImageURL);
                product.ImageURL = NewImageURL;
                db.SaveChanges();
                return RedirectToAction("index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories.ToList(), "ID", "Name");
            ViewBag.BrandID = new SelectList(db.Brands.ToList(), "ID", "Name");
            return View(product);

        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.NotFound);
            }
            var product = db.Products.SingleOrDefault(a => a.ID == id);
            ViewBag.CategoryID = new SelectList(db.Categories.ToList(), "ID", "Name");
            ViewBag.BrandID = new SelectList(db.Brands.ToList(), "ID", "Name");
            return View(product);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product product,HttpPostedFileBase ImageURL)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                FileInfo fi = new FileInfo(Server.MapPath("~/Images/ProductsImages/"+ product.ImageURL));
                fi.Delete();
                string NewImageURL = product.ID +"_"+ ImageURL.FileName;
                ImageURL.SaveAs(Server.MapPath("~/Images/ProductsImages/" + NewImageURL));
                product.ImageURL = NewImageURL;
                db.SaveChanges();
                return RedirectToAction("index");
                
            }
            ViewBag.CategoryID = new SelectList(db.Categories.ToList(), "ID", "Name");
            ViewBag.BrandID = new SelectList(db.Brands.ToList(), "ID", "Name");
            return View(product);
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }
            Product product = db.Products.Include(a=>a.Category).Include(a=>a.Brand).SingleOrDefault(a => a.ID == id);
            return View(product);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete (Product product)
        {
            var Deletedproduct = db.Products.Single(a => a.ID == product.ID);
            db.Products.Remove(Deletedproduct);
            db.SaveChanges();
            return RedirectToAction("index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
    
}

IdentityTask/Views/AdminProducts/Create.cshtml
@model IdentityTask.Models.Product
@{
    ViewBag.Title = "Create";
    ViewBag.Name = " Create Product";
    Layout = "~/Views/Shared/_layoutAdmin.cshtml";

}



@using (Html.BeginForm("Create", "AdminProducts", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal col-6" style="width:50%">
      
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(a => a.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(a => a.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(a => a.Name, null, new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(a => a.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(a => a.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(a => a.Description, null, new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(a => a.Price, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(a => a.Price, new { @class = "form-control" })
                @Html.ValidationMessageFor(a => a.Price, null, new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(a => a.Rate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(a => a.Rate, new { @class = "form-control" })
                @Html.ValidationMessageFor(a => a.Rate, null, new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(a => a.IsPopular, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(a => a.IsPopular)
                @Html.ValidationMessageFor(a => a.IsPopular, null, new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(a => a.ImageURL, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageURL" />
                @Html.ValidationMessageFor(a => a.Name, null, new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(a => a.Category, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(a => a.CategoryID, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(a => a.CategoryID, null, new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(a => a.Brand, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(a => a.BrandID, null, new { @class = "form-control" })
                @Html.ValidationMessageFor(a => a.BrandID, null, new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>

    @Html.ActionLink("Back To List", "index", null, new { @class = "btn" })
}

IdentityTask/Views/AdminProducts/Delete.cshtml
@model IdentityTask.Models.Product
@{
    ViewBag.Title = "Delete";
    ViewBag.Name = "Delete Product";
    Layout = "~/Views/Shared/_layoutAdmin.cshtml";

}


@using (Html.BeginForm("delete", "AdminProducts", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <h2> are you sure you want to delete this item</h2>
    @Html.Partial("Delete_Details")
    @*<div class="form-horizontal">
            <h2> are you sure you want to delete this item</h2>

            <dl>
                <dt>Product Image</dt>
                <dd><img src="~/Images/ProductsImages/@Model.ImageURL" style="border-radius:50%" height="70px" width="70px"></dd>
                <dt>Name</dt>
                <dd> @Model.Name</dd>
                <dt>Description</dt>
                <dd>@Model.Description</dd>
                <dt>Price</dt>
                <dd>@Model.Price</dd>
                <dt>Rate</dt>
                <dd>@Model.Rate</dd>
                <dt>Category</dt>
                <dd>@Model.Category.Name</dd>
                <dt>Brand</dt>
                <dd>@Model.Brand.Name</dd>
            </dl>
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>*@
}

IdentityTask/Views/AdminProducts/Delete_Details.cshtml
<div class="form-horizontal container col-lg-offset-3 font-weight-bold " style="font:20px black verdana" >
    <div class="row">
        

        <dl>
            <dt>Product Image</dt>
            <dd><img src="~/Images/ProductsImages/@Model.ImageURL" style="border-radius:50%" height="70px" width="70px"></dd>
            <dt>Name</dt>
            <dd> @Model.Name</dd>
            <dt>Description</dt>
            <dd>@Model.Description</dd>
            <dt>Price</dt>
            <dd>@Model.Price</dd>
            <dt>Rate</dt>
            <dd>@Model.Rate</dd>
            <dt>Category</dt>
            <dd>@Model.Category.Name</dd>
            <dt>Brand</dt>
            <dd>@Model.Brand.Name</dd>
        </dl>
        <input type="submit" value="Delete" class="btn btn-danger" />
    </div>
</div>
@Html.ActionLink("Back To List", "index", null, new { @class = "btn" })

IdentityTask/Views/AdminProducts/Details.cshtml
@model IdentityTask.Models.Product
@{
    ViewBag.Title = "Details";
    ViewBag.Name = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";

}

@Html.Partial("Delete_Details")

@*<table class="table table-bordered table-light" width="70%">
    <tr>
        <th>Image</th>
        <th>Category Name</th>
        <th>Brand Name</th>
        <th>Product Name</th>
        <th>Description</th>
        <th>Rate</th>
        <th>Price</th>
        <th>is Popular</th>

    </tr>

    <tr>
        <td>
            <img src="~/Images/ProductsImages/@Model.ImageURL" width="50px" height="50px" style="border-radius:50%" />
        </td>

        @if (@Model.Category != null)
        {
            <td>@Model.Category.Name</td>
        }
        else
        {
            <td>NoCategory</td>
        }
        
        <td>@Model.Brand.Name</td>
        <td>@Model.Name</td>
        <td>@Model.Description</td>
        <td>@Model.Rate</td>
        <td>@Model.Price</td>
        <td>@Model.IsPopular</td>
        <td>
            @Html.ActionLink("Details", "Details", "AdminProducts", new { id = Model.ID }, new { @class = "btn" })
        </td>
    </tr>

</table>
@Html.ActionLink("Back To List", "index", null, new { @class = "btn" })*@

IdentityTask/Views/AdminProducts/Edit.cshtml
@model IdentityTask.Models.Product
@{
    ViewBag.Title = "Edit";
    ViewBag.Name = "Edit Product";
    Layout = "~/Views/Shared/_layoutAdmin.cshtml";

}

@using (Html.BeginForm("Edit", "AdminProducts", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
<div class="form-horizontal col-6" style="width:50%">
    <h3 style="text-align:center">Edit Product</h3>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(a => a.ID)
    <div class="form-group">
        @Html.LabelFor(a => a.Name, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(a => a.Name, new { @class = "form-control" ,value=Model.Name})
            @Html.ValidationMessageFor(a => a.Name, null, new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(a => a.Description, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(a => a.Description, new { @class = "form-control" , value = Model.Description })
            @Html.ValidationMessageFor(a => a.Description, null, new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(a => a.Price, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(a => a.Price, new { @class = "form-control" })
            @Html.ValidationMessageFor(a => a.Price, null, new { @class = "text-danger",value=Model.Price })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(a => a.Rate, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(a => a.Rate, new { @class = "form-control" })
            @Html.ValidationMessageFor(a => a.Rate, null, new { @class = "text-danger" ,value=Model.Rate })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(a => a.IsPopular, new { @class = "control-label col-md-2" ,value=Model.IsPopular})
        <div class="col-md-10">
            @Html.CheckBoxFor(a => a.IsPopular)
            @Html.ValidationMessageFor(a => a.IsPopular, null, new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(a => a.ImageURL, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageURL" />
            @Html.ValidationMessageFor(a => a.Name, null, new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(a => a.Category, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(a => a.CategoryID, null, new { @class = "form-control" })
            @Html.ValidationMessageFor(a => a.CategoryID, null, new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(a => a.Brand, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(a => a.BrandID, null, new { @class = "form-control" })
            @Html.ValidationMessageFor(a => a.BrandID, null, new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Edit" class="btn btn-warning" />
        </div>
    </div>
</div>

    @Html.ActionLink("Back To List", "index", null, new { @class = "btn" })
}

IdentityTask/Views/AdminProducts/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IEnumerable<IdentityTask.Models.Product>
@{
    ViewBag.Title = "Index";
    ViewBag.Name = "Products";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="container row">

    <hr />
</div>
@using (Html.BeginForm("Index", "AdminProducts", FormMethod.Get))
{
    <div class="form-group ml-4 mb-4 row  " style="margin-left: 10px; width: 70%">
        <span>Search </span>  <input type="text" id="txtSearch" class="form-search" />
    </div>
    <div class="row ml-4" style="margin-left:10px">
        @Html.ActionLink("Add Product", "Create", "AdminProducts", new { @class = "btn btn-success ", style = "margin-top:5px;margin-left:5px" })

        @Html.ActionLink("Order by Name", "Index", new { SortOrder = ViewBag.RateSort }, new { @class = "btn btn-primary" })


        @Html.ActionLink("Order by NumberOfProducts", "Index", new { SortOrder = ViewBag.PriceSort }, new { @class = "btn btn-primary" })

    </div>

    <table class="table table-bordered table-light col-xs-9" cellspacing=1px cellpadding=1px width="70%">
        <tr>
            <th>Image</th>
            <th>Category Name</th>
            <th>Brand Name</th>
            <th>Product Name</th>
            <th>Description</th>
            <th>Rate</th>
            <th>Price</th>
            <th>is Popular</th>
            <th>Operations</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img src="~/Images/ProductsImages/@item.ImageURL" width="50px" height="50px" style="border-radius:50%" />
                </td>

                @if (@item.Category != null)
                {
                    <td>@item.Category.Name</td>
                }
                else
                {
                    <td>NoCategory</td>
                }

                <td>@item.Brand.Name</td>
                <td>@item.Name</td>
                <td>@item.Description</td>
                <td>@item.Rate</td>
                <td>@item.Price</td>
                <td>@item.IsPopular</td>
                <td>
                    @Html.ActionLink("Details", "Details", "AdminProducts", new { id = item.ID }, new { @class = "btn" })
                    @Html.ActionLink("Edit", "Edit", "AdminProducts", new { id = item.ID }, new { @class = "btn" })
                    @Html.ActionLink("Delete", "Delete", "AdminProducts", new { id = item.ID }, new { @class = "btn" })

                </td>
            </tr>
        }
    </table>
    <div style="text-align:center">
        @Html.PagedListPager(ViewBag.ProductsPerPage as IPagedList, page => Url.Action("Index", new { page, SortOrder = ViewBag.CurrentSort }))
        @*@Html.PagedListPager((IPagedList)ViewBag.CategoriesPerPage, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort }))*@
    </div>
}
@section scripts{

    <script>
        $(function () {
            $("#txtSearch").keyup(function () {
                var userInput = $(this).val();
                $("table:first tr:gt(0)").each(function (index, element) {
                    var currentValue = $(this).children("td:eq(1)").text()
                    if (currentValue.toLowerCase().indexOf(userInput.toLowerCase()) != -1) {
                        $(this).show();
                    }
                    else {
                        $(this).hide();
                    }
                })//end each
            })//end key
        })//end of load
    </script>
}